---
title: "team"
output: html_document
---

```{r} 

library(readxl)
library(tidyverse)
library(ggplot2)
defense <- read_excel('cyclonesFootball2020.xlsx', sheet='Defensive')
offensive <- read_excel('cyclonesFootball2020.xlsx', sheet='Offensive')
bio <- read_excel('cyclonesFootball2020.xlsx', sheet='Biography')
print(offensive)
```

Part One:
<br />
1.

```{r}

defense$Name <- as.factor(defense$Name)
defense$Opponent_Opponent <- as.factor(defense$Opponent_Opponent)

offensive$Name <- as.factor(offensive$Name)
offensive$Opponent_Opponent <- as.factor(offensive$Opponent_Opponent)

```
2.
```{r}

bioClean <- bio %>%
        mutate(Weight = as.numeric(Weight))



deffClean <- defense %>%
            mutate(across(Tackles_Solo:Pass_PB, as.numeric))

offClean <- offensive %>%
            mutate(across(Receiving_REC:Passing_INT, as.numeric))

```

3.
```{r}

bioClean <- bioClean %>% 
        separate(Height, c('Feet', 'Inches'), sep='-')

bioClean <- bioClean %>%
        mutate(Feet = as.numeric(Feet), Inches = as.numeric(Inches))

```

<br />
Part 2
<br />
1.
```{r}

offClean <- offClean %>%
              pivot_longer(cols = Receiving_REC:Passing_INT, names_to = "stat")

print(offClean)

```

2.
```{r}

ggplot(offClean, aes(value)) + geom_histogram(bins = 15) + facet_wrap(~ stat, scales = "free")

```

3.
```{r}

#print(offClean)

ok <- offClean %>%
      filter(stat == 'Receiving_YDS', Opponent_Opponent == 'Oklahoma')

or <- offClean %>%
      filter(stat == 'Receiving_YDS', Opponent_Opponent == 'Oregon')


ggplot(aes(x=value, y=Name), data=ok) + geom_point()
ggplot(aes(x=value, y=Name), data=or) + geom_point()

```
4.
```{r}

bioClean <- bioClean %>% 
              separate(Hometown, c('City', 'State'), sep=',')

```

5.
```{r}

bioClean %>%
          select(State) %>%
          group_by(State) %>%
          summarize(count = n())

```

<br />
Part 3 
<br />
1. 
```{r}

ggplot(bioClean, aes(State)) + geom_bar() + theme(axis.text.x = element_text(angle = 90)) 

```
2.
```{r}

brock <- offClean %>%
            filter(Name == "Purdy, Brock")


#brockSum <- brock %>%
              #summarize(totalPassTD = sum(Passing_TD), totalRushTD = sum(Rushing_TD), )

team <- offClean %>%
            filter(Name != 'Purdy, Brock')

#ggplot(brock, aes(x = Opponent_Opponent, y = Rushing_TD)) + geom_bar(stat = 'identity')

```


3.
```{r}

defense2019 <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
offense2019 <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
bio2019 <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')

defense2020 <- read_excel('cyclonesFootball2020.xlsx', sheet='Defensive')
offense2020 <- read_excel('cyclonesFootball2020.xlsx', sheet='Offensive')
bio2020 <- read_excel('cyclonesFootball2020.xlsx', sheet='Biography')


```

```{r}

deffClean19 <- defense2019 %>%
            mutate(across(Tackles_Solo:Pass_PB, as.numeric))

offClean19 <- offense2019 %>%
            mutate(across(Rushing_ATT:Passing_INT, as.numeric))

deffClean20 <- defense2020 %>%
            mutate(across(Tackles_Solo:Pass_PB, as.numeric))

offClean20 <- offense2020 %>%
            mutate(across(Receiving_REC:Passing_INT, as.numeric))

defSummary <- deffClean19 %>%
                group_by(Name) %>%
                mutate(Tackles_Total = Tackles_Solo + Tackles_ASST) %>%
                summarize(Total_Tackles=sum(Tackles_Total), )

defSummary20 <- deffClean %>%
                group_by(Name) %>%
                mutate(Tackles_Total = Tackles_Solo + Tackles_ASST) %>%
                summarize(Total_Tackles=sum(Tackles_Total), )

offClean19 <- offClean19 %>%
                group_by(Name) %>%
                summarize(totalReceivingTD = sum(Receiving_TD), totalRushingTD = sum(Rushing_TD), meanReceivingTD = mean(Receiving_TD), meanRushingTD = mean(Rushing_TD))
head(offClean19)

offCleanTemp <- offClean20 %>%
                group_by(Name) %>%
                summarize(totalReceivingTD = sum(Receiving_TD), totalRushingTD = sum(Rushing_TD), meanReceivingTD = mean(Receiving_TD), meanRushingTD = mean(Rushing_TD))

head(offCleanTemp)


```
This show that Breece Hall is the most improved player over 2019 through 2020.
